### PR TITLE
Added PriorityQueue implementation....

### PR DESCRIPTION
**Pull request by frankgiordano**
Added PriorityQueue implementation.... please merge if acceptable.. thank you, frank

### CODE REVIEW

**Comment by larrydiamond** [comment]
looks really nice now with the tests

the add method is supposed to return true if the collection changed as a
result of the add

a bunch of those should return true.....


+ it("Test adding items to priority queue and hitting capacity", function()
{
+ const PriorityQueue1:PriorityQueue<PetStoreProduct> = new PriorityQueue<
PetStoreProduct>(3, alphabeticalSortPetStoreProduct);
+ expect (PriorityQueue1.size()).toEqual(0);
+ expect (PriorityQueue1.add(product1)).toEqual(false);
+ expect (PriorityQueue1.size()).toEqual(1);
+ expect (PriorityQueue1.add(product2)).toEqual(false);
+ expect (PriorityQueue1.size()).toEqual(2);
+ expect (PriorityQueue1.add(product3)).toEqual(false);
+ expect (PriorityQueue1.size()).toEqual(3);
+ expect (PriorityQueue1.add(product4)).toEqual(false);
+ expect (PriorityQueue1.size()).toEqual(3);
+ expect (PriorityQueue1.isEmpty()).toEqual(false);
+ });
+

**Comment by larrydiamond** [comment]
btw, really nice work and really close to getting accepted into the
framework :)

**Comment by frankgiordano** [comment]
checked in a fix, please review and merge if acceptable..  btw opened a bug reported related to why I was using false initially for pQueue add() method..

**Comment by larrydiamond** [comment]
Awesome, lets discuss live today, great research and thank you!

**Comment by larrydiamond** [comment]
GASP. Bug Confirmed.

Thank you very much, you are absolutely correct and I'm feeling embarrassed today.

You will be listed as a contributor for finding and reporting this bug with my thanks this weekend.

I should have realized when I saw the wrong return code coming from your code it was because I had the wrong return code coming from my code   :)

**Pull request merged**
